### ISSUE TITLE
 RES's Never ending list header update

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Windows-theme#22]
![](https://cdn.discordapp.com/attachments/150662382874525696/243789081488785408/2016-11-03_12-27-56.png)

**Browser font compatibility**
- [x] Chrome
- [x] Firefox
- [ ] latest IE
- [ ] Edge
- [ ] Safari

- [ ] SASS variables for symbol fonts

**Comment by gofirst2220** [comment]
@Jasius This is what I did to make the changes

``` CSS
:root{
    --font: "Segoe UI", "Helvetica Neue", Helvetica, Arial, Verdana, sans-serif;
    --icons: "Segoe MDL2 Assets", "Segoe UI Symbol";
}
.content {
    border: 0 solid transparent !important;
    outline: none !important;
    margin-right: 0;
    padding-right: 0;
    background-color: transparent !important;
}
.res .sitetable .sitetable {
    border: 0 solid transparent !important;
    outline: none !important;
}
.res-ner-listing {
    display: inherit !important;
    visibility: visible;
    border-right: 5px solid #d7ecff !important;
    font-family: var(--font) !important;
    background-color: transparent !important;
}
.link {
    border: 0 solid transparent !important;
    outline: none !important;
    font-family: var(--font) !important;
}
#siteTable .thing {
    border-top: 0 solid transparent !important;
    border-right: 0 solid transparent !important;
    border-bottom: 1px solid #d7ecff !important;
    outline: none !important;
    padding-right: 0 !important;
    margin-right: 0px;
    margin-top: 0;
    background-image: none !important;
}
.NERPageMarker {
    border-radius: 0 !important;
    background-color: #0057A6 !important;
    background-size: contain !important;
    background-image: none !important;
    background-repeat: no-repeat !important;
    color: white !important;
    border-bottom: none !important;
    outline: none !important;
    margin-right: -10px;
    margin-top: 0px;
    margin-bottom: 0px;
    padding: 10px;
    font-weight: 400;
    font-size: 13px;
    border-right: 5px solid #1992FF !important;
    z-index: 2 !important;
}
.NERPageMarker:after {
    display: block;
    position: absolute;
    z-index: -1 !important;
    border-color: transparent transparent transparent #d7ecff;
    border-width: 10px;
    border-style: solid;
    content: "";
    margin-right: 0px;
    margin-left: 75.4%;
    margin-top: 0%;
    background-color: transparent !important;
    background-size: contain !important;
    color: #d7ecff;
    outline: none !important;
}
.NERPageMarker .gearIcon {
    border: none !important;
    border-radius: 0 !important;
    width: auto !important;
    background-color: transparent !important;
    color: white !important;
    background-image: none !important;
    background-size: contain !important;
    background-repeat: no-repeat !important;
    font-family: var(--icons) !important;
    text-align: right !important;
    display: inline-block !important;
    position: relative !important;
    outline: none !important;
}
.NERPageMarker .gearIcon:after {
    text-indent: 0px !important;
    color: white !important;
    content: "\E713" !important;
    background-image: none !important;
    background-repeat: no-repeat !important;
    background-size: contain !important;
    font-family: var(--icons) !important;
    text-align: center !important;
    background-color: transparent !important;
    outline: none !important;
    border: none !important;
}
```
